# Generated by Django 5.2.3 on 2025-11-17 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CREAM", "cream"),
                            ("WHOLE MILK", "whole milk"),
                            ("SKIMMED MILK", "skimmed milk"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_product_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_product_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreamProductDefinition",
            fields=[],
            options={
                "verbose_name": "Cream product definition",
                "verbose_name_plural": "Cream product definitions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("product_definitions.productdefinition",),
        ),
        migrations.CreateModel(
            name="SkimmedMilkProductDefinition",
            fields=[],
            options={
                "verbose_name": "Skimmed milk product definition",
                "verbose_name_plural": "Skimmed milk product definitions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("product_definitions.productdefinition",),
        ),
        migrations.CreateModel(
            name="WholeMilkMilkProductDefinition",
            fields=[],
            options={
                "verbose_name": "While milk product definition",
                "verbose_name_plural": "While milk product definitions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("product_definitions.productdefinition",),
        ),
    ]
