# Generated by Django 5.2.3 on 2025-12-04 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milk", "0002_remove_milk_storage_type"),
        ("producers", "0001_initial"),
        ("storages", "0002_delete_containerstorage_delete_silostorage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="milk",
            index=models.Index(
                fields=["created_at"], name="milk_milk_created_bd493e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="milk",
            index=models.Index(
                fields=["producer", "created_at"], name="milk_milk_produce_c62dd9_idx"
            ),
        ),
    ]
