# Generated by Django 5.2.3 on 2025-12-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("milk", "0003_milk_milk_milk_created_bd493e_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="milk",
            name="producer_uuid",
        ),
        migrations.RemoveField(
            model_name="milk",
            name="storage_uuid",
        ),
    ]
