# Generated by Django 5.2.3 on 2025-12-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("milk", "0004_remove_milk_producer_uuid_remove_milk_storage_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="milk",
            name="producer_name",
        ),
        migrations.RemoveField(
            model_name="milk",
            name="storage_name",
        ),
    ]
