# Generated by Django 5.2.3 on 2025-09-15 21:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasteurisedMilk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("pasteur_id", models.CharField(max_length=255)),
                ("pasteur_name", models.CharField(max_length=255)),
                ("source_storage_id", models.CharField(max_length=255)),
                ("source_storage_name", models.CharField(max_length=255)),
                (
                    "source_storage_type",
                    models.CharField(
                        choices=[
                            ("SILO", "silo"),
                            ("TUB", "tub"),
                            ("CONTAINER", "container"),
                        ],
                        max_length=255,
                    ),
                ),
                ("target_storage_id", models.CharField(max_length=255)),
                ("target_storage_name", models.CharField(max_length=255)),
                (
                    "target_storage_type",
                    models.CharField(
                        choices=[
                            ("SILO", "silo"),
                            ("TUB", "tub"),
                            ("CONTAINER", "container"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "volume_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1.0)]
                    ),
                ),
                (
                    "volume_liters",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1.0)]
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(-273.15)]
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pasteurised_milk",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_pasteurised_milk",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
