# Generated by Django 5.2.3 on 2025-11-23 19:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StorageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("code_name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
