# Generated by Django 5.2.3 on 2025-09-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_deleted_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
