# Generated by Django 5.2.3 on 2025-09-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_profile_last_name_alter_profile_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
