# Generated by Django 5.2.3 on 2025-09-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_deleted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
