# Generated by Django 5.2.3 on 2025-11-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pasteurisation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pasteurisation",
            name="source_storage_type",
        ),
        migrations.RemoveField(
            model_name="pasteurisation",
            name="target_storage_type",
        ),
    ]
