# Generated by Django 5.2.3 on 2025-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pasteurisation", "0002_remove_pasteurisation_source_storage_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pasteurisation",
            name="product_definition_type",
        ),
        migrations.AddField(
            model_name="pasteurisation",
            name="product_definition_uuid",
            field=models.CharField(default="", editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
