# Generated by Django 5.2.3 on 2025-12-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "pasteurisation",
            "0003_remove_pasteurisation_product_definition_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pasteurisation",
            name="pasteur_name",
        ),
        migrations.RemoveField(
            model_name="pasteurisation",
            name="pasteur_uuid",
        ),
        migrations.RemoveField(
            model_name="pasteurisation",
            name="product_definition_name",
        ),
        migrations.RemoveField(
            model_name="pasteurisation",
            name="product_definition_uuid",
        ),
        migrations.RemoveField(
            model_name="pasteurisation",
            name="source_storage_name",
        ),
        migrations.RemoveField(
            model_name="pasteurisation",
            name="source_storage_uuid",
        ),
        migrations.RemoveField(
            model_name="pasteurisation",
            name="target_storage_name",
        ),
        migrations.RemoveField(
            model_name="pasteurisation",
            name="target_storage_uuid",
        ),
    ]
