# Generated by Django 5.2.3 on 2025-09-25 10:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producers", "0001_initial"),
        ("storages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Milk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("producer_uuid", models.CharField(editable=False, max_length=255)),
                ("producer_name", models.CharField(editable=False, max_length=255)),
                (
                    "volume_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1.0)]
                    ),
                ),
                (
                    "volume_liters",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1.0)]
                    ),
                ),
                ("storage_uuid", models.CharField(editable=False, max_length=255)),
                ("storage_name", models.CharField(editable=False, max_length=255)),
                (
                    "storage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SILO", "silo"),
                            ("TUB", "tub"),
                            ("CONTAINER", "container"),
                        ],
                    ),
                ),
                (
                    "acid_content",
                    models.FloatField(
                        blank=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("aflatoxin", models.BooleanField(blank=True)),
                ("inhibitory_residue", models.BooleanField(blank=True)),
                (
                    "temperature",
                    models.FloatField(
                        blank=True,
                        validators=[django.core.validators.MinValueValidator(-273.15)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_milk",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_milk",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produced_milk",
                        to="producers.producer",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stored_milk",
                        to="storages.storage",
                    ),
                ),
            ],
        ),
    ]
