# Generated by Django 5.2.3 on 2025-09-11 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milk",
            name="acid_content",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="milk",
            name="temperature",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(-273.15)]
            ),
        ),
        migrations.AlterField(
            model_name="milk",
            name="volume_kg",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1.0)]
            ),
        ),
        migrations.AlterField(
            model_name="milk",
            name="volume_liters",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1.0)]
            ),
        ),
    ]
