# Generated by Django 5.2.3 on 2025-12-06 19:47
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmetadata",
            name="uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
