# Generated by Django 5.2.3 on 2025-12-06 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_groups", "0003_fill_uuids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmetadata",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
