# Generated by Django 5.2.3 on 2025-09-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "producers",
            "0002_alter_producer_created_by_alter_producer_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="producer",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="producer",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
