FROM node:24.2-alpine AS builder

WORKDIR /src
COPY src/frontend/. .
RUN npm ci --silent
RUN npm run build

FROM nginx:alpine


COPY --from=builder /src/dist /usr/share/nginx/html/frontend

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/nginx.frontend.conf /etc/nginx/conf.d/frontend.conf