# ------------------------
# Base Python stage
# ------------------------
	FROM python:3.13-alpine3.21 AS base

	RUN addgroup -S app && adduser -S app -G app
	WORKDIR /app
	
	# Environment setup
	ENV PYTHONPATH=/app/src \
		PYTHONDONTWRITEBYTECODE=1 \
		PYTHONUNBUFFERED=1
	
	# Install Python and Postgres build deps
	RUN apk add --no-cache \
		build-base \
		libpq \
		libpq-dev \
		python3-dev \
		musl-dev \
		curl \
		git
	
	USER app
	
	# Install pip deps
	COPY requirements.txt .
	RUN pip install --upgrade pip && pip install -r requirements.txt
	
	# ------------------------
	# Frontend build stage
	# ------------------------
	FROM node:24.2-alpine AS builder
	
	WORKDIR /src
	COPY src/frontend/. .
	RUN npm ci --silent
	RUN npm run build
	
	# ------------------------
	# Final Django runtime stage
	# ------------------------
	FROM base AS final
	
	COPY --chown=app:app src/backend /app/src/backend
	COPY --from=builder /src/dist /app/src/frontend/dist
	
	# Expose ports
	EXPOSE 8080
		
	# Run Django app
	CMD ["python3", "src/manage.py", "runserver", "0.0.0.0:8080"]