# Generated by Django 5.2.3 on 2025-12-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storages", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContainerStorage",
        ),
        migrations.DeleteModel(
            name="SiloStorage",
        ),
        migrations.DeleteModel(
            name="TubStorage",
        ),
        migrations.AlterField(
            model_name="storage",
            name="type",
            field=models.CharField(
                choices=[("SILO", "silo"), ("TUB", "tub"), ("CONTAINER", "container")],
                max_length=255,
            ),
        ),
    ]
