# Generated by Django 5.2.3 on 2025-11-23 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage_types", "0002_storage_type_metadata"),
        ("storages", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContainerStorage",
        ),
        migrations.DeleteModel(
            name="SiloStorage",
        ),
        migrations.DeleteModel(
            name="TubStorage",
        ),
        migrations.RemoveField(
            model_name="storage",
            name="type",
        ),
        migrations.AddField(
            model_name="storage",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="storage",
                to="storage_types.storagetype",
            ),
        ),
    ]
