# Generated by Django 5.2.3 on 2025-09-16 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("storages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_storages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storage",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_storages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ContainerStorage",
            fields=[],
            options={
                "verbose_name": "Container",
                "verbose_name_plural": "Containers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("storages.storage",),
        ),
        migrations.CreateModel(
            name="SiloStorage",
            fields=[],
            options={
                "verbose_name": "Silo",
                "verbose_name_plural": "Silos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("storages.storage",),
        ),
        migrations.CreateModel(
            name="TubStorage",
            fields=[],
            options={
                "verbose_name": "Tub",
                "verbose_name_plural": "Tubs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("storages.storage",),
        ),
    ]
